[package]
name = "html2maud-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "html2maud"
path = "src/main.rs"

[dependencies]
html2maud = { path = "../library" }
clap = { version = "4.0.32", features = ["derive"] }
